<?=$this->render("header.phtml")?>

<?php if (isset($this->error)) { ?>

    <span class="alert-error">The following errors where found</span>

    <ul>
        <?php foreach ($this->error as $error) { ?>
            <li><?= $error ?></li>
        <?php } ?>
    </ul>

<?php } ?>

<div class="row">
    <div class="span12">
        <h1>Create a new raffle</h1>
        <form class="form" method="POST" action="/create">
            <label>Name</label><input type="text" name="name"/>
            <label>Number of Winners</label><input type="text" name="winners"/>
            <br/>
            <input type="submit" value="Create" class="btn btn-success"/>
        </form>
    </div>
</div>
<?=$this->render("footer.phtml")?>